### PR TITLE
about upgrade to ffi 2.0.1

### PR DESCRIPTION
**Pull request by Guo8a**
Hello, after I upgrading the flutter version to 3.10.0, I found that the version of the tflite_helper library is too low and depends on ffi1.0.0.
I found you forked the branch and upgrade ffi and image version, I also found you create a new branch named "downgrade-ffi" and hold ffi version to 1.0.0. 
Any question you found after upgrade?
I'd be more than happy to discuss this with you. Thank you for your patience.

### CODE REVIEW

**Comment by Guo8a** [comment]
@pnyompen

**Comment by pnyompen** [comment]
Hello,

Thank you for your email and interest in the tflite_flutter updates. Yes, I did create a "downgrade-ffi" branch. This is due to the tflite_flutter 0.9.0 library, which my project is currently utilizing, being dependent on ffi1.0.0.

With the latest tflite_flutter 0.9.5, unfortunately, the models don't seem to function properly in my iOS environment. Hence, I found it necessary to downgrade and maintain the ffi version at 1.0.0.

Best regards,

**Comment by Apach3Q** [comment]
> Hello,
> 
> Thank you for your email and interest in the tflite_flutter updates. Yes, I did create a "downgrade-ffi" branch. This is due to the tflite_flutter 0.9.0 library, which my project is currently utilizing, being dependent on ffi1.0.0.
> 
> With the latest tflite_flutter 0.9.5, unfortunately, the models don't seem to function properly in my iOS environment. Hence, I found it necessary to downgrade and maintain the ffi version at 1.0.0.
> 
> Best regards,
Sure, thank you for your response. I also noticed that some method return values changed after upgrading the image library (such as getPixel). I will make some changes and test it based on your branch. Thank you for the pull request.
Best regards.

**Comment by Guo8a** [comment]
> Hello,
> 
> Thank you for your email and interest in the tflite_flutter updates. Yes, I did create a "downgrade-ffi" branch. This is due to the tflite_flutter 0.9.0 library, which my project is currently utilizing, being dependent on ffi1.0.0.
> 
> With the latest tflite_flutter 0.9.5, unfortunately, the models don't seem to function properly in my iOS environment. Hence, I found it necessary to downgrade and maintain the ffi version at 1.0.0.
> 
> Best regards,

Sure, thank you for your response. I also noticed that some method return values changed after upgrading the image library (such as getPixel). I will make some changes and test it based on your branch. Thank you for the pull request.
Best regards.

**Comment by Guo8a** [comment]
@pnyompen 
I noticed that in version 3.0.2 of the image library, `image.data` represents "Pixels are encoded into 4-byte Uint32 integers in #AABBGGRR channel order." 
Therefore, when you upgraded the image library, you changed the old `image.data` to `image.data!.buffer.asUint32List()`. 
However, I noticed in the downgrade-ffi branch you deprecated this code and changed it to `w*h`. 
I am wondering if the downgrade-ffi branch is also not a completely correct version and needs further modification? Currently, I am using your master branch and have not encountered any issues. 
I am only using the face recognition functionality. 
Do you have any insights on this?

**Comment by pnyompen** [comment]
@Apach3Q 
Thank you for your detailed inquiry regarding the image library updates and your usage of the face recognition functionality.

I'd like to clarify that the implementation in the master branch was indeed incorrect, and the corrected implementation can be found in the downgrade-ffi branch. The issue arises when the numChannels of the image isn't 4. In such cases, the conversion doesn't function correctly.

I've used the following experimental code to illustrate this:

```
final image = Image(width: 100, height: 100, numChannels: 4);
final imageBuffer = image.data!.buffer.asUint32List();
print('imageBuffer length: ${imageBuffer.length}');
print('width * height: ${image.width * image.height}');
print('image numChannels: ${image.numChannels}');
```
Output:
```
imageBuffer length: 10000
width * height: 10000
image numChannels: 4
```
In this case, when the numChannels is 4, the imageBuffer length and width*height values are equal, so there's no issue.

However, when the numChannels isn't 4, as in the following example where numChannels is 3, the values change:

```
final image = Image(width: 100, height: 100, numChannels: 3);
final imageBuffer = image.data!.buffer.asUint32List();
print('imageBuffer length: ${imageBuffer.length}');
print('width * height: ${image.width * image.height}');
print('image numChannels: ${image.numChannels}');
```
Output:
```
imageBuffer length: 7500
width * height: 10000
image numChannels: 3
You can see that when the numChannels is 3, the values vary.
```

Please note that we've made the necessary corrections to the upgrade-camera-image-packages branch. It would be greatly appreciated if you could use this updated version.

https://github.com/pnyompen/tflite_flutter_helper/commit/43e87d4b9627539266dc20250beb35bf36320dce

Best regards,

**Comment by Guo8a** [comment]
@pnyompen 
Thank you for your patient explanation! 
I am lacking in knowledge about image-related topics, so I appreciate your answers to my questions. 
I will use your updated branch. 
Hopefully, we can work together to monitor and improve the quality of the tflite_flutter library and related packages!

**Comment by Guo8a** [comment]
Currently, I am using the improved library by pnyompen, which temporarily solves the issue of incompatibility with ffi 2.0.1. 
Therefore, I will close this pull request. 
If there are any new updates in the future, please kindly notify me. 
Thank you and best regards.

**Pull request closed without merging**
